// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: citizen/citizens_owned.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CitizensOwned struct {
	Owner      string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	CitizenIds []string `protobuf:"bytes,2,rep,name=citizenIds,proto3" json:"citizenIds,omitempty"`
}

func (m *CitizensOwned) Reset()         { *m = CitizensOwned{} }
func (m *CitizensOwned) String() string { return proto.CompactTextString(m) }
func (*CitizensOwned) ProtoMessage()    {}
func (*CitizensOwned) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfbb77dad746d1ab, []int{0}
}
func (m *CitizensOwned) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CitizensOwned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CitizensOwned.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CitizensOwned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitizensOwned.Merge(m, src)
}
func (m *CitizensOwned) XXX_Size() int {
	return m.Size()
}
func (m *CitizensOwned) XXX_DiscardUnknown() {
	xxx_messageInfo_CitizensOwned.DiscardUnknown(m)
}

var xxx_messageInfo_CitizensOwned proto.InternalMessageInfo

func (m *CitizensOwned) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CitizensOwned) GetCitizenIds() []string {
	if m != nil {
		return m.CitizenIds
	}
	return nil
}

func init() {
	proto.RegisterType((*CitizensOwned)(nil), "demoonechain.citizen.CitizensOwned")
}

func init() { proto.RegisterFile("citizen/citizens_owned.proto", fileDescriptor_bfbb77dad746d1ab) }

var fileDescriptor_bfbb77dad746d1ab = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xce, 0x2c, 0xc9,
	0xac, 0x4a, 0xcd, 0xd3, 0x87, 0xd2, 0xc5, 0xf1, 0xf9, 0xe5, 0x79, 0xa9, 0x29, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x22, 0x29, 0xa9, 0xb9, 0xf9, 0xf9, 0x79, 0xa9, 0xc9, 0x19, 0x89, 0x99,
	0x79, 0x7a, 0x50, 0x25, 0x4a, 0xae, 0x5c, 0xbc, 0xce, 0x50, 0xd5, 0xfe, 0x20, 0xc5, 0x42, 0x22,
	0x5c, 0xac, 0x20, 0x5d, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x1c,
	0x17, 0x17, 0x54, 0x87, 0x67, 0x4a, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x92, 0x88,
	0x93, 0xf9, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1,
	0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xc9, 0x82, 0xac, 0xd5,
	0x85, 0xd9, 0xab, 0x5f, 0x01, 0x73, 0x9c, 0x7e, 0x49, 0x65, 0x41, 0x6a, 0x71, 0x12, 0x1b, 0xd8,
	0x71, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xec, 0x8d, 0xd5, 0xbc, 0x00, 0x00, 0x00,
}

func (m *CitizensOwned) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CitizensOwned) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CitizensOwned) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CitizenIds) > 0 {
		for iNdEx := len(m.CitizenIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CitizenIds[iNdEx])
			copy(dAtA[i:], m.CitizenIds[iNdEx])
			i = encodeVarintCitizensOwned(dAtA, i, uint64(len(m.CitizenIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCitizensOwned(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCitizensOwned(dAtA []byte, offset int, v uint64) int {
	offset -= sovCitizensOwned(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CitizensOwned) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCitizensOwned(uint64(l))
	}
	if len(m.CitizenIds) > 0 {
		for _, s := range m.CitizenIds {
			l = len(s)
			n += 1 + l + sovCitizensOwned(uint64(l))
		}
	}
	return n
}

func sovCitizensOwned(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCitizensOwned(x uint64) (n int) {
	return sovCitizensOwned(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CitizensOwned) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCitizensOwned
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CitizensOwned: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CitizensOwned: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCitizensOwned
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCitizensOwned
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCitizensOwned
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizenIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCitizensOwned
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCitizensOwned
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCitizensOwned
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CitizenIds = append(m.CitizenIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCitizensOwned(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCitizensOwned
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCitizensOwned(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCitizensOwned
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCitizensOwned
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCitizensOwned
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCitizensOwned
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCitizensOwned
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCitizensOwned
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCitizensOwned        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCitizensOwned          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCitizensOwned = fmt.Errorf("proto: unexpected end of group")
)
