// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: citizen/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the citizen module's genesis state.
type GenesisState struct {
	Params             Params           `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Owner              *Owner           `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CitizenList        []Citizen        `protobuf:"bytes,3,rep,name=citizenList,proto3" json:"citizenList"`
	CitizenOwnerList   []CitizenOwner   `protobuf:"bytes,4,rep,name=citizenOwnerList,proto3" json:"citizenOwnerList"`
	CitizenIdsList     []CitizenIds     `protobuf:"bytes,5,rep,name=citizenIdsList,proto3" json:"citizenIdsList"`
	CitizenIdsCount    uint64           `protobuf:"varint,6,opt,name=citizenIdsCount,proto3" json:"citizenIdsCount,omitempty"`
	CitizensOwnedList  []CitizensOwned  `protobuf:"bytes,7,rep,name=citizensOwnedList,proto3" json:"citizensOwnedList"`
	ApprovalList       []Approval       `protobuf:"bytes,8,rep,name=approvalList,proto3" json:"approvalList"`
	ApprovalForAllList []ApprovalForAll `protobuf:"bytes,9,rep,name=approvalForAllList,proto3" json:"approvalForAllList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_72b027f04af8f12c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOwner() *Owner {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *GenesisState) GetCitizenList() []Citizen {
	if m != nil {
		return m.CitizenList
	}
	return nil
}

func (m *GenesisState) GetCitizenOwnerList() []CitizenOwner {
	if m != nil {
		return m.CitizenOwnerList
	}
	return nil
}

func (m *GenesisState) GetCitizenIdsList() []CitizenIds {
	if m != nil {
		return m.CitizenIdsList
	}
	return nil
}

func (m *GenesisState) GetCitizenIdsCount() uint64 {
	if m != nil {
		return m.CitizenIdsCount
	}
	return 0
}

func (m *GenesisState) GetCitizensOwnedList() []CitizensOwned {
	if m != nil {
		return m.CitizensOwnedList
	}
	return nil
}

func (m *GenesisState) GetApprovalList() []Approval {
	if m != nil {
		return m.ApprovalList
	}
	return nil
}

func (m *GenesisState) GetApprovalForAllList() []ApprovalForAll {
	if m != nil {
		return m.ApprovalForAllList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "demoonechain.citizen.GenesisState")
}

func init() { proto.RegisterFile("citizen/genesis.proto", fileDescriptor_72b027f04af8f12c) }

var fileDescriptor_72b027f04af8f12c = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x4d, 0x8f, 0xd2, 0x40,
	0x1c, 0xc6, 0x5b, 0x79, 0x51, 0x07, 0xe2, 0xcb, 0x88, 0xa6, 0xf2, 0x32, 0x36, 0xe8, 0xa1, 0x17,
	0xdb, 0x88, 0x07, 0x13, 0x6f, 0x40, 0x7c, 0x21, 0x31, 0x6a, 0xd0, 0xc4, 0x84, 0x0b, 0xa9, 0x74,
	0xc4, 0x26, 0xd0, 0x69, 0xda, 0xee, 0xeb, 0xa7, 0xd8, 0x64, 0xbf, 0x14, 0x47, 0x8e, 0x7b, 0xda,
	0x6c, 0xe0, 0x8b, 0x6c, 0xfa, 0x9f, 0xff, 0xec, 0xb2, 0xa5, 0xe9, 0x69, 0x98, 0xe7, 0xff, 0x3c,
	0xbf, 0x87, 0x19, 0x06, 0xf2, 0x7c, 0xe6, 0x27, 0xfe, 0x29, 0x0f, 0x9c, 0x39, 0x0f, 0x78, 0xec,
	0xc7, 0x76, 0x18, 0x89, 0x44, 0xd0, 0x86, 0xc7, 0x97, 0x42, 0x04, 0x7c, 0xf6, 0xdf, 0xf5, 0x03,
	0x1b, 0x3d, 0xcd, 0xc6, 0x5c, 0xcc, 0x05, 0x18, 0x9c, 0xf4, 0x93, 0xf4, 0x36, 0x1b, 0x0a, 0x11,
	0xba, 0x91, 0xbb, 0x44, 0x42, 0xf3, 0x99, 0x52, 0xc5, 0x51, 0xc0, 0x23, 0x14, 0x6f, 0xda, 0x70,
	0x45, 0xb9, 0x95, 0x91, 0xa7, 0xbb, 0x99, 0x97, 0xd9, 0xa1, 0xef, 0xa9, 0x8e, 0x76, 0x66, 0x14,
	0x43, 0xd0, 0xc3, 0xe9, 0x0b, 0x35, 0x75, 0xc3, 0x30, 0x12, 0x87, 0xee, 0x02, 0x75, 0x96, 0xd5,
	0xa7, 0xff, 0x44, 0x34, 0x75, 0x17, 0x38, 0xef, 0x9e, 0x57, 0x48, 0xfd, 0x8b, 0xbc, 0x8d, 0x5f,
	0x89, 0x9b, 0x70, 0xfa, 0x91, 0x54, 0xe5, 0xd1, 0x0c, 0xdd, 0xd4, 0xad, 0x5a, 0xaf, 0x6d, 0xe7,
	0xdd, 0x8e, 0xfd, 0x13, 0x3c, 0x83, 0xf2, 0xea, 0xf2, 0x95, 0x36, 0xc6, 0x04, 0x7d, 0x47, 0x2a,
	0x70, 0x18, 0xe3, 0x1e, 0x44, 0x5b, 0xf9, 0xd1, 0x1f, 0xa9, 0x65, 0x2c, 0x9d, 0xf4, 0x13, 0xa9,
	0xa1, 0xfe, 0xcd, 0x8f, 0x13, 0xa3, 0x64, 0x96, 0xac, 0x5a, 0xaf, 0x93, 0x1f, 0x1c, 0xca, 0x15,
	0x4b, 0x77, 0x73, 0xf4, 0x37, 0x79, 0x82, 0x5b, 0xa0, 0x03, 0xab, 0x0c, 0xac, 0x6e, 0x21, 0x0b,
	0xdc, 0x08, 0xdc, 0x23, 0xd0, 0xef, 0xe4, 0x11, 0x6a, 0x23, 0x2f, 0x06, 0x66, 0x05, 0x98, 0x66,
	0x21, 0x73, 0xe4, 0xa9, 0x7b, 0xc9, 0xa4, 0xa9, 0x45, 0x1e, 0xdf, 0x2a, 0x43, 0x71, 0x10, 0x24,
	0x46, 0xd5, 0xd4, 0xad, 0xf2, 0x38, 0x2b, 0xd3, 0x3f, 0xe4, 0xa9, 0xfa, 0x99, 0xd3, 0xaf, 0xe3,
	0x41, 0xf9, 0x7d, 0x28, 0x7f, 0x5d, 0x58, 0x2e, 0xed, 0xd8, 0xbf, 0xcf, 0xa0, 0x5f, 0x49, 0x5d,
	0xbd, 0x04, 0x60, 0x3e, 0x00, 0x26, 0xcb, 0x67, 0xf6, 0xd1, 0x89, 0xb8, 0x3b, 0x49, 0x3a, 0x21,
	0x54, 0xed, 0x3f, 0x8b, 0xa8, 0xbf, 0x90, 0xbc, 0x87, 0xc0, 0x7b, 0x53, 0xcc, 0x93, 0x7e, 0xa4,
	0xe6, 0x50, 0x06, 0x1f, 0x56, 0x1b, 0xa6, 0xaf, 0x37, 0x4c, 0xbf, 0xda, 0x30, 0xfd, 0x6c, 0xcb,
	0xb4, 0xf5, 0x96, 0x69, 0x17, 0x5b, 0xa6, 0x4d, 0x3a, 0x29, 0xf8, 0xad, 0x22, 0x3b, 0xc7, 0xea,
	0xdf, 0xe0, 0x24, 0x27, 0x21, 0x8f, 0xff, 0x56, 0xe1, 0x55, 0xbf, 0xbf, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xe7, 0x16, 0x98, 0x7e, 0xea, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ApprovalForAllList) > 0 {
		for iNdEx := len(m.ApprovalForAllList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApprovalForAllList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.ApprovalList) > 0 {
		for iNdEx := len(m.ApprovalList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApprovalList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.CitizensOwnedList) > 0 {
		for iNdEx := len(m.CitizensOwnedList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CitizensOwnedList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.CitizenIdsCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CitizenIdsCount))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CitizenIdsList) > 0 {
		for iNdEx := len(m.CitizenIdsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CitizenIdsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.CitizenOwnerList) > 0 {
		for iNdEx := len(m.CitizenOwnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CitizenOwnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.CitizenList) > 0 {
		for iNdEx := len(m.CitizenList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CitizenList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Owner != nil {
		{
			size, err := m.Owner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Owner != nil {
		l = m.Owner.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.CitizenList) > 0 {
		for _, e := range m.CitizenList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CitizenOwnerList) > 0 {
		for _, e := range m.CitizenOwnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CitizenIdsList) > 0 {
		for _, e := range m.CitizenIdsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CitizenIdsCount != 0 {
		n += 1 + sovGenesis(uint64(m.CitizenIdsCount))
	}
	if len(m.CitizensOwnedList) > 0 {
		for _, e := range m.CitizensOwnedList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ApprovalList) > 0 {
		for _, e := range m.ApprovalList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ApprovalForAllList) > 0 {
		for _, e := range m.ApprovalForAllList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Owner == nil {
				m.Owner = &Owner{}
			}
			if err := m.Owner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizenList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CitizenList = append(m.CitizenList, Citizen{})
			if err := m.CitizenList[len(m.CitizenList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizenOwnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CitizenOwnerList = append(m.CitizenOwnerList, CitizenOwner{})
			if err := m.CitizenOwnerList[len(m.CitizenOwnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizenIdsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CitizenIdsList = append(m.CitizenIdsList, CitizenIds{})
			if err := m.CitizenIdsList[len(m.CitizenIdsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizenIdsCount", wireType)
			}
			m.CitizenIdsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CitizenIdsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CitizensOwnedList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CitizensOwnedList = append(m.CitizensOwnedList, CitizensOwned{})
			if err := m.CitizensOwnedList[len(m.CitizensOwnedList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovalList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovalList = append(m.ApprovalList, Approval{})
			if err := m.ApprovalList[len(m.ApprovalList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovalForAllList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApprovalForAllList = append(m.ApprovalForAllList, ApprovalForAll{})
			if err := m.ApprovalForAllList[len(m.ApprovalForAllList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
